name: Fabrica de Instalador de Zeins

on:
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargando codigo
      uses: actions/checkout@v4

    - name: Configurando Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalando Librerias
      run: |
        pip install customtkinter mammoth pandas OpenPyXL python-pptx markdownify pyinstaller

    - name: 1. Crear el EXE base
      run: |
        pyinstaller --noconsole --onefile --name "Convertidor_MKD_V1" convertidor_pro.py

    - name: 2. Crear el Instalador (.msi/.exe)
      uses: AyimDomini/innosetup-action@v1.0.1
      with:
        filepath: setup.iss

    - name: 3. Guardar Instalador Final
      uses: actions/upload-artifact@v4
      with:
        name: Instalador_Zeins_Completo
        path: dist/Instalador_Convertidor_Zeins.exe
