name: Fabrica de EXE de Zeins

on:
  workflow_dispatch: # Esto permite que tú actives la creación con un botón

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Descargando codigo
      uses: actions/checkout@v4

    - name: Configurando Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Instalando Librerias Necessarias
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter mammoth pandas OpenPyXL python-pptx markdownify pyinstaller

    - name: Compilando el programa a EXE
      run: |
        pyinstaller --noconsole --onefile --name "Convertidor_Zeins_V1" convertidor_pro.py

    - name: Guardar el resultado para descargar
      uses: actions/upload-artifact@v4
      with:
        name: Programa_MD_Listo
        path: dist/Convertidor_Zeins_V1.exe
